#!/usr/bin/env bash

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

case "$1" in
	build)
		cd "$SCRIPT_DIR"
		protoc -Iproto-messages --python_out=. proto-messages/*
	;;
esac

